### ISSUE TITLE
California Error for Chevy Bolt EV or EUV

### ISSUE THREAD

**Issue by MarVistaSocial** [Ben-Chapman/EVFinder#91]
**Describe the bug**
The EV Finder is not working when searching for a Chevy Bolt EV or EUV for California zip codes. The error message is "Hmm, There's Been an Error. There was a server error with this request. Please refresh this page or retry."

** The EV Finder Version and Debug Information:**
- Visit https://theevfinder.com/debug
- Copy and paste the information presented on that page here: 
NoSuchKeyThe specified key does not exist.

**To Reproduce**
1. Go to theevfinder.com
2. Click on Year: 2023, Make/Model: Bolt EUV, Zip Code: 90404, Distance: 200
3. See error

**Expected behavior**
A list of available or in-transit cars.

**Device and Web Browser:**
 - iPhone 12, Safari
 - MacbookPro 2022, Safari 

**Additional context**

**Comment by Ben-Chapman** [comment]
hey @MarVistaSocial thanks for the report.

I see what's going on and I'll get it fixed in the next couple of hours - sorry for the inconvenience.

**Comment by MarVistaSocial** [comment]
Thanks so much, Ben!

**Comment by Ben-Chapman** [comment]
I just shipped the fix for this issue, so you should be good to go with a page refresh.

The issue was, there's one vehicle (VIN: 1G1FZ6S08P4156766) in this area which does not have a dealer assigned yet. This caused an error in one of the helper functions which is used for formatting text on the site.

[Here's the fix](https://github.com/Ben-Chapman/EVFinder/commit/b3622defdf9c18cd9bb427d7d0e19f17105655bf#diff-f252d970a769a6fdb9a918240735f0938f9b1caf51e4ffea2247957827255927) if you're interested.

Thanks again for reporting this!

**Comment by MarVistaSocial** [comment]
Hi @Ben-Chapman, thanks for addressing that bug. Although, now it seems that all the searches are timing out before any results pop up. Any idea why that might be? Happy to open a new ticket if that's the procedure.

Here's the error I'm getting:

"Hmm, There's Been an Error

There was a server error with this request: timeout of 15000ms exceeded
Please refresh this page or retry."

Thanks for any attention you can give to this! Hoping to buy one of these cars today.

**Comment by Ben-Chapman** [comment]
It looks like there was an issue with the Chevrolet inventory system earlier today, which has since been resolved. Please let me know if you're still having issues.
